### ISSUE TITLE
Find registers when value is null

### ISSUE THREAD

**Issue by hjJunior** [Jaguar-dart/jaguar_orm#109]
I'm using Jaguar ORM for Flutter, and I'm having issue to find a register where int field is null, is it supported?

## Scenario
On my model I have `externalId` 

```dart
  @Column(isNullable: true)
  int externalId;
```

And on the bean I created a method to get only where externalId doesn't have value 
```dart
await findMany(finder.where(externalId.eq(null)));
```

But this return to me none registers, but I can see that exists registers with `externalId` null, to confirm it, I called to getAll() and printed 

```
[Model {id: 1, externalId: 13 }, Model {id: 2, externalId: 14 }, Model {id: 3, externalId: null }]
```

**Comment by tejainece** [comment]
@hjJunior `IS NULL` operator is needed for this. It is being implemented here:

https://github.com/Jaguar-dart/jaguar_orm/pull/107

**Comment by tejainece** [comment]
Use `jaguar_query` `2.2.5`. There is an `iss` operator.

**Comment by tejainece** [comment]
@hjJunior I think this is fixed. Please reopen the issue if you find issues.

**Comment by hjJunior** [comment]
thxs :)
