### ISSUE TITLE
Discussion about orderBy

### ISSUE THREAD

**Issue by hjJunior** [Jaguar-dart/jaguar_orm#112]
I was writing a query where I was supposed to manipulate the columns, basically, I've `externalId` where is Null or an integer, so my objetive it was order first if `externalId` is null late by the date

Basicaly this raw query it works very nice
```dart
"SELECT * FROM $tableName ORDER BY CASE WHEN ${externalId.name} IS NULL THEN 0 ELSE 1 END, ${dtCreated.name} DESC"
```

But I not got to use on `orderBy` because of definition standard
```dart
.orderBy('(CASE WHEN ${externalId.name} IS NULL THEN 0 ELSE 1)')

// Definition
  Find orderBy(String column, [bool ascending = false]) {
    _orderBy.add(OrderBy(column, ascending));
    return this;
  }

  Find orderByMany(List<String> columns, [bool ascending = false]) {
    columns.forEach((String column) {
      _orderBy.add(OrderBy(column, ascending));
    });
    return this;
  }

// and on compose
String composeOrderBy(final OrderBy orderBy) =>
    '${orderBy.columnName} ' + (orderBy.ascending ? 'ASC' : 'DESC');

```
I was thinking about allow user send null to avoid breaking changes, and another thing, it was allow on orderByMany  ascending be List<bool>

**Comment by tejainece** [comment]
Looking into this.

**Comment by tejainece** [comment]
@hjJunior I will fix this.

@jaumard Can you fix this in sqlite adapter and take care of it being null?

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/2f2f90a37e386bf4537157f60646f1b91615ac2f
