### ISSUE TITLE
Missing "part 'user.jorm.dart';"

### ISSUE THREAD

**Issue by rodolfoggp** [Jaguar-dart/jaguar_orm#118]
I'm trying to follow this tutorial: 
https://github.com/Jaguar-dart/jaguar_orm/wiki/Generating-ORM-for-simple-table

But when I run "flutter pub pub run build_runner build" to generate the _UserBean class, apparently it doesn't work. How can I find this generated class?

I'm also getting this on my terminal:

[INFO] Running build...
[WARNING] jaguar_orm_gen on lib/model/user.dart:
Generating bean for UserBean ...
[WARNING] jaguar_orm_gen on lib/model/user.dart:
**Missing "part 'user.jorm.dart';".**
[INFO] Running build completed, took 1.0s

**Comment by tejainece** [comment]
@rodolfoggp Add the following line in your `user.dart` file:

```
part 'user.jorm.dart';
```

`user.jorm.dart` file is generated by the when you run `pub run build_runner build`.

**Comment by tejainece** [comment]
I have also updated the wiki page to reflect this.
