### ISSUE TITLE
Add support to foreign-primary key columns

### ISSUE THREAD

**Issue by isaacfi** [Jaguar-dart/jaguar_orm#121]
I'm trying to add a foreign-primary key using PrimaryKey and BelongsTo annotations, but I have this error:

Exception: Only one Column annotation is allowed on a Field!
#0      ParsedBean._makeField ([package:jaguar_orm_gen/src/parser/parser.dart:360:7](https://github.com/Jaguar-dart/jaguar_orm/blob/master/generator/lib/src/parser/parser.dart))

The Partner class (foreign-primary key)

```
class Partner {
  @PrimaryKey(length: 32)
  @BelongsTo(UserBean, refCol: 'userId')
  String partnerId;
  @Column()
  int gender;
}
```

And in the other one User class

```
class User {
  @PrimaryKey(length: 32)
  String userId;
  @Column(length: 50)
  String firstName;
  @Column(isNullable: true, length: 50)
  String lastName;
  @HasOne(PartnerBean)
  Partner partner;
}
```

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_orm/pull/124.
