### ISSUE TITLE
Drop database statement is incorrect

### ISSUE THREAD

**Issue by JamesMcIntosh** [Jaguar-dart/jaguar_orm#128]
I went to use the drop database statement but it tried to create a database instead.
 
```
String composeDropDb(final DropDb st) => "CREATE DATABASE ${st.name}";
```
Should be
```
String composeDropDb(final DropDb st) => "DROP DATABASE ${st.name}";
```

https://github.com/Jaguar-dart/jaguar_orm/blob/07c3b63e8b4c5646ac157385cb0268c2c2be3560/sqflite/lib/src/compose/delete.dart#L20

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/ff219bc1fb7eccc034b87db6e461ba7a27269a72.

Published to pub as `2.2.10`.
