### ISSUE TITLE
Compose find for sqflite adapter wrong

### ISSUE THREAD

**Issue by mikeroneer** [Jaguar-dart/jaguar_orm#132]
The `GROUP BY` clause is always the very last clause in the `SELECT` statement, no matter in which order the calling code orders the clauses. This leads to an SQL exception when used together with `ORDER BY` or `LIMIT`. 
According to https://www.sqlite.org/syntaxdiagrams.html#select-stmt, this is invalid syntax.

**Comment by tejainece** [comment]
I am guessing this issue is fixed. Please reopen if that is not the case.
