### ISSUE TITLE
Fine grained ORM column annotations

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_orm#136]

**Comment by tejainece** [comment]
New annotations: https://github.com/Jaguar-dart/jaguar_orm/blob/master/orm/lib/src/annotations/nextgen.dart

**Comment by JamesMcIntosh** [comment]
@tejainece 
Hi Ravi, I think one of the most well developed solutions for annotating data models for ORM consumption would be the JPA specification, picking a subset of their annotations could help with structure and bring the annotation names inline with other similar projects to help with developers coming new to dart.

http://www.techferry.com/articles/hibernate-jpa-annotations.html
https://www.doctrine-project.org
https://typeorm.io
https://docs.microsoft.com/en-us/aspnet/entity-framework

**Comment by JamesMcIntosh** [comment]
@tejainece I see you have a new annotation [Foreign](https://github.com/Jaguar-dart/jaguar_orm/blob/master/orm/lib/src/annotations/nextgen.dart#L30), is that to accommodate one sided foreign relationships?

**Comment by tejainece** [comment]
I have pushed more new changes. Check it and let me know what you think.

**Comment by tejainece** [comment]
This is implemented.
