### ISSUE TITLE
Feature request: debug option for adapter

### ISSUE THREAD

**Issue by pafik13** [Jaguar-dart/jaguar_orm#144]
It would be nice to be able to track all queries.

I think it should be something like this:

```
final PgAdapter _adapter =
    new PgAdapter('example', username: 'postgres', password: 'dart_jaguar');
await _adapter.connect(debug: true);   // or (printAllQueries: true)
```

**Comment by tejainece** [comment]
Great idea. I will implement this.

**Comment by tejainece** [comment]
Implemented by https://github.com/Jaguar-dart/jaguar_orm/commit/5e209222cfb95018405a58e06451c3dd5e75d1fd
