### ISSUE TITLE
Dart SDK v2 support ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [Jaguar-dart/jaguar_orm#15]
Dear all,

any idea as to when the maintainers of this package will expand compatibility to Dart SDK v2 ?

**Comment by tejainece** [comment]
Starting work on it tonight

**Comment by sandrobilbeisi** [comment]
;-)

**Comment by tejainece** [comment]
A little late. But jaguar_orm has been upgraded to Dart2 by https://github.com/Jaguar-dart/jaguar_orm/commit/73ec8d28746229a5a1725123fe0a99b11df9cee2
