### ISSUE TITLE
Is there a Sum() function available?

### ISSUE THREAD

**Issue by ziakhan110** [Jaguar-dart/jaguar_orm#151]
i need to create this query in orm
select sum(amount) from transaction group by category_id order by amount desc limit 3;

this my table
![db](https://user-images.githubusercontent.com/8199129/61114827-94d6a000-a4aa-11e9-905a-3e7fdaba5489.png)

**Comment by jaumard** [comment]
Hello,

No I don't think this kind of request are supported by the ORM, but look like you don't need an ORM for those, just execute a raw query no ?
