### ISSUE TITLE
how to achieve limit

### ISSUE THREAD

**Issue by YourksChan** [Jaguar-dart/jaguar_orm#152]
SELECT c1,c2,cn... FROM table WHERE id>=20000 LIMIT 10;

**Comment by ishaan1995** [comment]
@YourksChan 
If you generated your beans, there is a finder method inside the bean which allows limit query.

Eg: 

Let's say your table name is `User` and generated bean is `UserBean`.

```
List<User> users = await userBean.findMany(userBean.finder.gtEq('id', 20000).limit(10));
```

**Comment by YourksChan** [comment]
> @YourksChan
> If you generated your beans, there is a finder method inside the bean which allows limit query.
> 
> Eg:
> 
> Let's say your table name is `User` and generated bean is `UserBean`.
> 
> ```
> List<User> users = await userBean.findMany(userBean.finder.gtEq('id', 20000).limit(10));
> ```

Thanks!
