### ISSUE TITLE
Further work on this plugin

### ISSUE THREAD

**Issue by boskokg** [Jaguar-dart/jaguar_orm#156]
Hi there,

I would like to know if you have any plans on working further on this plugin or you are going to leave it as it is.

The current master is unstable and I see there was no work done in the last 3 months.

The last stable release makes me the conflict with the other plugins because of an old version of analyzer dependency.

I am using your plugin in the big project and if you cannot maintain the plugin, please tell me so I can search for the alternative to use.

Thanks.

**Comment by jaumard** [comment]
We are in the same case as you :) but worse case scenario, we will have to fork the code, update it and publish it again with another name, at least that's what we plan to do if needed.  
In the same time you can use dependency_overrides to force the analyzer version

**Comment by boskokg** [comment]
I have done the fork and updated the entire code to 4.x.x.
I made a marge request, but no one responds to it for weeks.
I am using my fork for now and it works pretty well...

**Comment by jaumard** [comment]
Interesting ! 
What is more on 4.x.x that wasn't in 3.x.x ?

**Comment by boskokg** [comment]
Actually, I don't know. I saw the changes that contributors made on postgres and done the same thing on sqflite.

**Comment by boskokg** [comment]
jaumard, would you like to create a separate plugin for sqflite and continue improvements out of this unmaintained plugin?

**Comment by jaumard** [comment]
ho ok ! I'm waiting because I'm talking with the maintainer to know if I can have rights to deploy the package on pub, I already have rights on GitHub but not yet on pub. If I have the rights I prefer not to create a separate repo and keep maintaining this one to keep the name and community.
I'll keep you in the loop :)

**Comment by jaumard** [comment]
So @boskokg I've got some news :) I was able to reach the maintainer a he add me to pub/github so I'm able to maintain this project. 
I'll will check you PR about v4 but might take time as I need to understand was this version offers, but I'll check that. I'm closing this issue :)
