### ISSUE TITLE
package:jaguar_orm_postgresql/jaguar_orm_postgresql.dart'. doesn not exist 

### ISSUE THREAD

**Issue by maheshj01** [Jaguar-dart/jaguar_orm#160]
I saw the examples and you are importing
``` jaguar_orm_postgresql/jaguar_orm_postgresql.dart'```
I have included jaguar_orm as well as jaguar_query but still the error persist?

**Comment by jaumard** [comment]
Hello,

Do you have a repo who reproduce this error ? I'm currious about it, it shouldn't append

**Comment by maheshj01** [comment]
I dont have it for now we can close this issue If I find something I will reopen it with a an example repo including the steps on how to reproduce the error
