### ISSUE TITLE
jaguar_query: Add transaction

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_orm#17]
Implement transaction begin, rollback and commit on `Adapter` interface

**Comment by erwintan96** [comment]
is it still in progress?

**Comment by Swat2k** [comment]
some question...

**Comment by tejainece** [comment]
Working on this. Will be part of Jaguar ORM 4.x.x.

**Comment by tejainece** [comment]
This is implemented for query, Adapter and Bean.

Generator should also support this in generated methods.

**Comment by tejainece** [comment]
This is now completely implemented.
