### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#21]
In order to use (or knowing if we can) jaguar in enterprise environment we need to have a license. I look several repository of jaguar that might save us a lot of time lol but can't use them until we know which license you put on those repo 
Thanks

**Comment by kevin-sakemaer** [comment]
All jaguar project use the same license iirc, you should find the license file next to the pubspec.yaml of the project.
for the orm you can found it here https://github.com/Jaguar-dart/jaguar_orm/blob/master/orm/LICENSE

**Comment by jaumard** [comment]
Ho I'm used to find them a root level of the project lol sorry :D I should have more... 
Thanks a lot
