### ISSUE TITLE
findAll and findWhere cascade/preload

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#33]
Just notice that those method can't load associations (or I miss something ^^), might be a nice addition

**Comment by jaumard** [comment]
Just notice the preload and preloadAll methods but preloadAll is empty for many to many ^^
I'll a preloadWhere would be useful

**Comment by tejainece** [comment]
Will fix it.

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/8909999aecfedad503c80500434ec3aa5df040f8
