### ISSUE TITLE
UpdateAll and insertAll method

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#34]
Would be nice to have to be able to make bulk operation, will be also faster to do one request will all model than loop on all of them to insert/update

**Comment by jaumard** [comment]
Hey :) I want to look into this, do you have an idea on how implement this or not ? 
I was looking to modify the Insert and Update class to add a `bulk(List<Map<String, dynamic>> values)` method on it.
Then we can have `final List<Map<String, dynamic>> _bulkValues = [];`, then adapters must be updated to check if it's a bulk insert/update and do whatever needed in both cases.
What do you think  @tejainece ?

**Comment by tejainece** [comment]
Lets first do the `InsertMany` and then move on to `UpdateMany`.

How about a new `InsertMany` class and `insertMany` method on the adapter? Same goes for `UpdateMany`.

**Comment by jaumard** [comment]
Hum ok let go that way see how it goes, at least no breaking changes for the other method :) I'll start trying the InsertMany :)

**Comment by tejainece** [comment]
Yes. Also interface of `Insert` stay clean.

**Comment by tejainece** [comment]
`InsertMany` is complete I suppose? Can you also send a pull request for `UpdateMany`?

With that we can launch `2.2.x` version.

**Comment by jaumard** [comment]
Yes insert many is complete I think, I started the updateMany but my lack of SQL make me struggle on what update sql request should I create for sqlite :/ once I figure that out I'll make a PR :)

**Comment by jaumard** [comment]
I think this one is all good now :) closing it
