### ISSUE TITLE
Logo Design Offer For JAGUAR ORM

### ISSUE THREAD

**Issue by iqbalhood** [Jaguar-dart/jaguar_orm#38]
Hello Sir. I'm a UI/UX and Graphics Designer. who has contacted you via email last week.
These are my logo proposal for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

# Version 1
![jaguar with name app](https://user-images.githubusercontent.com/1563756/42995735-c55e52be-8c3b-11e8-83fb-d624a4e81b6a.jpg)

# Version 2

![jaguar with name app 2](https://user-images.githubusercontent.com/1563756/42995751-cec73df2-8c3b-11e8-8933-424febbcfdff.jpg)

**Comment by tejainece** [comment]
Wow! Love it!

**Comment by tejainece** [comment]
Looks fantastic! I think we can use this across all Jaguar projects.

**Comment by iqbalhood** [comment]
Well, thanks, What kind of Files do you need? I Will provide it for you

**Comment by jaumard** [comment]
Look very good job ! :) love V2 more but both are good !

**Comment by tejainece** [comment]
@iqbalhood ico, png and webp would be great. 

If you can provide photoshop or some editable vector format along with it to make miner changes later, that would be great too.

**Comment by iqbalhood** [comment]
Hello Sir, This is All of the file format that you request.
https://drive.google.com/drive/folders/1rvP-j3yQa5Ps75471en_YQ3yO37JswgG?usp=sharing

I've also created a pull request to add a logo and modify the Readme.md file
https://github.com/Jaguar-dart/jaguar_orm/pull/44

**Comment by tejainece** [comment]
Thanks Iqbal!

The pull request is now merged. Your logo is now Jaguar's official logo.

Thanks for the great work!

**Comment by iqbalhood** [comment]
@tejainece is my logo accepted for jaguar_orm?

**Comment by tejainece** [comment]
Yes. Its on the front page.

I will soon put it on the web page too here: https://jaguar-dart.github.io/

**Comment by tejainece** [comment]
Oh my god! Sorry for the typo.

I meant "Your logo is now Jaguar's official logo.". Not "Your logo is not Jaguar's official logo.".

**Comment by iqbalhood** [comment]
okay sir , thanks for the confirmation :) 👍

**Comment by kevin-sakemaer** [comment]
Hi @iqbalhood,
Thanks a lot for this amazing logo.
Could you provide a logo only that is a square ? like that we can also put it as the logo of the jaguar organization ?
Actually the logo only png is 446 width and 424 height
Thanks

**Comment by tejainece** [comment]
@Kleak He delivered it. You can get it from here: https://drive.google.com/drive/folders/1ViMubdB_WGmSEojG8foBSjbl3Doq5YF0

**Comment by kevin-sakemaer** [comment]
It's not a square 😕
If we use it the logo will be cut on a side
