### ISSUE TITLE
If id is Int, insert method not gen correctly with association

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#40]
In SQLite, if you want an auto increment id, you need to put it as int, by doing so the insert method is not generated correctly in case of association:
```
Future<dynamic> insert(Post model, {bool cascade: false}) async {
    final Insert insert = inserter.setMany(toSetColumns(model))..id(id);
  
```
Problem is that id method of Insert is waiting for a String not an int so it complain

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/e71b5a8a874c7b725d529986fb79cebe9663c037
