### ISSUE TITLE
Possibility to ignore fields during generation on getters

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#41]
I have this model: 

```
class CartDb {
  @PrimaryKey(autoIncrement: true)
  int id;

  @HasMany(CartItemDbBean)
  List<CartItemDb> items;
  double amount;

  CartDb({this.id, this.amount = 0.0, this.items = const []});

  String get amountLabel {
    return kNumberFormat.format(amount);
  }

  @override
  String toString() => 'amount=$amount, items=$items';

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is CartDb && runtimeType == other.runtimeType && items == other.items && amount == other.amount;

  @override
  int get hashCode => items.hashCode ^ amount.hashCode;

}
```

The problem with this is that during generation, it's generating stuff for `amountLabel ` and `hashCode`. 
Would be nice if the generator can automatically ignore those fields (don't know if it's possible or not) or at least having some kind of @ignore annotation maybe to just don't generate anything related to those :)

**Comment by tejainece** [comment]
Is this what you are looking for: https://pub.dartlang.org/documentation/jaguar_orm/latest/jaguar_orm/IgnoreColumn-class.html?

**Comment by jaumard** [comment]
Indeed ! Didn't see this one :) just tested but look like it doesn't work ^^ just tested on my example like this : 
```
class CartDb {
  @PrimaryKey(autoIncrement: true)
  int id;

  @HasMany(CartItemDbBean)
  List<CartItemDb> items;
  double amount;

  CartDb({this.id, this.amount = 0.0, this.items = const []});

  String get amountLabel {
    return kNumberFormat.format(amount);
  }

  @override
  String toString() => 'amount=$amount, items=$items';

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is CartDb && runtimeType == other.runtimeType && items == other.items && amount == other.amount;

  @override
  @IgnoreColumn()
  int get hashCode => items.hashCode ^ amount.hashCode;

}
```
but it still generate me all the stuff to map/set/use it :(

**Comment by jaumard** [comment]
Oups just read on model so I guess I use it wrong let me test this ^^

**Comment by jaumard** [comment]
Hum nope as we can't specify which column we want to ignore so I guess my first try should be the way to use it :/

**Comment by tejainece** [comment]
Does it work like this?

```dart
class CartDb {
  ...

  @override
  @IgnoreColumn()
  int get hashCode => items.hashCode ^ amount.hashCode;
}
```

**Comment by tejainece** [comment]
It should also work like this:

```
@GenBean(
  columns: {
    'hashCode': const IgnoreColumn(),
  }
)
```

**Comment by jaumard** [comment]
Not that was my first try but it still generate hashCode stuff :(

**Comment by jaumard** [comment]
```
@GenBean(
  columns: {
    'hashCode': const IgnoreColumn(),
  }
)
```
This one works great :) but the notation directly on the field looks better :p

**Comment by tejainece** [comment]
Notation directly on the field works for fields. It seems to now work for **getters**. Will fix it.

**Comment by jaumard** [comment]
Ho ok ! Tricky one :)

**Comment by tejainece** [comment]
Fixed in https://github.com/Jaguar-dart/jaguar_orm/commit/2cfe558703d0f32c3ccca56b9e45b7147351b4da. Also published.

**Comment by jaumard** [comment]
That was fast thanks ^^ :) I'll check that

**Comment by tejainece** [comment]
Here is an example showing different ways to ignore: https://github.com/Jaguar-dart/jaguar_orm/blob/master/orm/example/model/basic/ignore_column.dart#L24

**Comment by tejainece** [comment]
`hashCode` and `runtimeType` are ignored by default

**Comment by tejainece** [comment]
> but the notation directly on the field looks better

Definitely. But Jaguar ORM and Jaguar Serializer also supports spec `@Gen*` so that model and serialization/database code can be kept separate and shared between server and client.

It is quite flexible. So you can put the annotations on both the places.

**Comment by tejainece** [comment]
Let me know if this has fixed the issue.

**Comment by jaumard** [comment]
Yes fixed for me :) thanks !
