### ISSUE TITLE
@Column nullable ignored

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#46]
Apparently nullable on column doesn't work:

I tried this: 
```
@Column(nullable: true)
  String product;
```
or 
```
@GenBean(
  columns: {
    'product': Column(nullable: true),
  },
)
```
But both generate this:
`st.addStr(product.name);`
instead of 
`st.addNullStr(product.name);`

**Comment by tejainece** [comment]
Yes. Known issue. Will fix this.

**Comment by tejainece** [comment]
Was waiting to clean up `jaguar_query` api. `addNull*` is going away. Just `addStr(name, isNullable: true)`.

**Comment by jaumard** [comment]
Nice will help also later for `isUnique`, `isIndex` 👍

**Comment by tejainece** [comment]
`isNullable` and `uniqueGroup` has been added by https://github.com/Jaguar-dart/jaguar_orm/commit/a3cb1d9a45afeb29cb530333681470639450c084.

Please create new issue for `index`.
