### ISSUE TITLE
Upgrade jaguar_query_sqflite package to 2.2.x

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_orm#50]

**Comment by tejainece** [comment]
@jaumard Could you please upgrade `jaguar_query_sqflite` package to `2.2.x`?

One of the breaking changes is merging of `Col` and `Field` into `Field`. There are some minor simplifying changes too. You could use `jaguar_query_postgres` package for reference.

Thanks.

**Comment by jaumard** [comment]
Sure :) let me look at this :)

**Comment by jaumard** [comment]
@tejainece jaguar_query has strong dependency on jaguar_query_postgres where it should be the opposite jaguar_query shouldn't know about jaguar_query_postgres at all.
jaguar_query_postgres is put as dev_dep even if not only for dev. 
I say that because jaguar_query_postgres doesn't work with flutter as it use an SDK too recent for now.

**Comment by jaumard** [comment]
Also you have change update(tableName) from update()..into(tableName) but Find and Insert didn't change, I don't think is good to have different notation, it should be align

**Comment by tejainece** [comment]
`jaguar_query_postgres ` is just a dev dependency. So there are some real life examples directly in the query repo. There is no actual dependence.

**Comment by tejainece** [comment]
That change is based on how we describe it in english. 

> Update this table with these rows.

> Insert these rows in into this table

I have fixed the `Find` according to your suggestions.

> FInd from this table where this expression select these fields

**Comment by tejainece** [comment]
Will also change insert statement according to your suggestions. Maybe consistency is more important that correlation with English language.

**Comment by jaumard** [comment]
Hum in my opinion consistency is more important, even more because Insert(tableName) don't throw any error as it's a correct statement (it will probably crash at runtime)

**Comment by tejainece** [comment]
Changed insert.
