### ISSUE TITLE
Sqflite adapter SDK update and example update

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#55]
https://github.com/jaguar-orm/sqflite is broken with last sqflite adapter (master) 

Also now that flutter beta has a new version with dart 2 stable, the adapter need to update his `environment` to be usable in new flutter version

@tejainece can you help on this ? I'm stuck with a crash in the generator :( `The getter 'type' was called on null.` on many to many example

**Comment by tejainece** [comment]
Does this occur with https://github.com/jaguar-orm/sqflite

**Comment by jaumard** [comment]
Yes :)

**Comment by tejainece** [comment]
I have no time today. Will try to fix it tomorrow.

**Comment by jaumard** [comment]
No problem @tejainece can't manage to find where is the problem here ^^

**Comment by tejainece** [comment]
This I think is fixed? Please reopen if the problem still exists.
