### ISSUE TITLE
Single quote ' text not escaped on insert

### ISSUE THREAD

**Issue by juliusspencer** [Jaguar-dart/jaguar_orm#56]
Hi,

I'm using Flutter and have generated my class using:
`flutter packages pub run build_runner build`

I'm getting rows inserted into the database. 😀 However I'm having trouble with some items not being added because they contain a single quote in their text. 😕(eg. "MTHEM8101'CP")

`flutter: DatabaseException(Error Domain=FMDatabase Code=1 "near "CP": syntax error" UserInfo={NSLocalizedDescription=near "CP": syntax error}) sql 'INSERT INTO product(sku, name, category_id) VALUES ('MTHEM8101'CP', 'Echo Minimalist Basin Mixer Chrome', 1117629706)' args []}`

Is this something I should be doing when creating assigning my object parameters? 🤔 I thought that the generated class would handle.

Thanks for any help.

**Comment by tejainece** [comment]
Will fix this.

**Comment by juliusspencer** [comment]
Thank you Ravi!

By the way, where is there a suitable place to ask questions?

**Comment by jaumard** [comment]
@juliusspencer I'll say the jaguar Gitter channel is the better place for this :)

**Comment by tejainece** [comment]
This is fixed in latest version of jaguar_query_sqflite. Please test it and close the issue if it is fixed.

Thanks.
