### ISSUE TITLE
Code generator generating duplicate bean get properties.

### ISSUE THREAD

**Issue by ethimjos-velo** [Jaguar-dart/jaguar_orm#73]
**Problem**: In some cases, depending on the relation between entities, the code generator 
generates duplicate get properties for beans. Below is an example of a generated bean class:

```dart
   ....
   ....
   ....
   BookUserBean get bookUserBean;

   UserBean get userBean;
   AuthorBean get authorBean;
   UserBean get userBean; /*Duplicate*/
   PublisherBean get publisherBean;
}
```
The problem occurs in the first loop of the **_writeBeans()** function that deals with preloads. If the preload **p** is **PreloadManyToMany**, the writer writes the targetBean get property but does't keep track of it as a written property by adding it into the **written** set. 

```dart
....
....
....
if (p is PreloadManyToMany) {
        _writeln('');
        _write(p.targetBeanName);
        _write(' get ');
        _write(p.targetBeanInstanceName);
        _writeln(';');
}
....
....
....
```
The duplicate property is written when the last loop of the **_writeBeans()** that deals with **fields** executes. 
The same thing might happen inside the second loop.[**Not tested**]

```dart
//Third loop.
for (Field f in _b.fields.values) {
	if (f.foreign is BelongsToForeign) {
		BelongsToForeign fb = f.foreign;

                //The logic for checking if the property is generated before is present 
                //but because when the targetBean is generated in the first loop it 
                //is not inserted into the written set, the written.contains(...)
                //returns false and the property is generated again resulting in a duplicate
                //get property.
		if (written.contains(fb.beanInstanceName)) continue; 

		written.add(fb.beanInstanceName);

		_write(fb.beanName);
		_write(' get ');
		_write(fb.beanInstanceName);
		_writeln(';');
	}
}
```

**Cause**:  Missing condition and statement for checking if a property has been generated before and for adding it into the _written_ set, inside the _if_ block that deals with _PreloadManyToMany_.

**Suggested Fix**: Modify the _PreloadManyToMany if_ block from this:

```dart
....
....
....
if (p is PreloadManyToMany) {
        _writeln('');
        _write(p.targetBeanName);
        _write(' get ');
        _write(p.targetBeanInstanceName);
        _writeln(';');
}
....
....
....
```
to this:

```dart
....
....
....
if (p is PreloadManyToMany) {
        //Check if the property for the p.targetBeanInstanceName has been generated before.
	if (written.contains(p.targetBeanInstanceName)) continue;

        //Add the p.targetBeanInstanceName into the written set if the property has not been 
        //generated before.
	written.add(p.targetBeanInstanceName);
      	
	_writeln('');
	_write(p.targetBeanName);
	_write(' get ');
	_write(p.targetBeanInstanceName);
	_writeln(';');
}
....
....
....
```

**Comment by tejainece** [comment]
Thanks for very clean insights into how to fix the issue. Saved a ton of my time. If you have time, you can send PR yourself. PRs are always welcome :).

The issue should be fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/33087976aee625ecb1b4308b3f5983d442f29fd1

Try `jaguar_orm_gen` version `2.2.14` in pub.

Please close the issue if it has been fixed.

Thanks!

**Comment by tejainece** [comment]
Hi,

Is this fixed?

**Comment by ethimjos-velo** [comment]
Hello!
I tested the suggested fix before creating the issue and it works. I haven't been able to pull the new version and try it but since it only contains the suggested changes that I  already tested I will consider the problem fixed and close the issue. I will try the new version on Monday and if something is wrong I will open this issue again.
Thanks for your great work!
