### ISSUE TITLE
Wrong library name for generator.

### ISSUE THREAD

**Issue by ethimjos-velo** [Jaguar-dart/jaguar_orm#75]
**Problem** : _jaguar_orm_gen_ and _jaguar_serializer_cli_ cannot be used at the same time because of a conflicting library name. As a result the build process fails for both packages.

**Cause** : The library name inside _generator/lib/builder.dart_ is not correctly defined. The actual library name is jaguar_serializer_cli. 

````dart
library jaguar_serializer_cli; //Wrong name.

import 'package:build/build.dart';
import 'src/hook/hook.dart';
import 'package:source_gen/source_gen.dart';

Builder jaguarSerializerPartBuilder({String header}) =>
    PartBuilder([BeanGenerator()], '.jorm.dart', header: header);

Builder jaguarOrm(BuilderOptions options) =>
    jaguarSerializerPartBuilder(header: options.config['header'] as String);
````

**Suggested Fix**: Change the library name from jaguar_serializer_cli to jaguar_orm_gen.

````dart
library jaguar_orm_gen; //Correct name.

import 'package:build/build.dart';
import 'src/hook/hook.dart';
import 'package:source_gen/source_gen.dart';

Builder jaguarSerializerPartBuilder({String header}) =>
    PartBuilder([BeanGenerator()], '.jorm.dart', header: header);

Builder jaguarOrm(BuilderOptions options) =>
    jaguarSerializerPartBuilder(header: options.config['header'] as String);
````

**Comment by tejainece** [comment]
Thanks for the report!

Fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/53984dd22afc96fe28fb06d55c56441d95918499.

Published as `2.2.16`.

Please reopen the issue if it persists.
