### ISSUE TITLE
Visit HasMany from BelongsTo? Is there a better way?

### ISSUE THREAD

**Issue by junjizhi** [Jaguar-dart/jaguar_orm#81]
In your Post-Item [one-to-many example](https://github.com/jaguar-orm/sqflite/blob/master/lib/one_to_many/item.dart), you have to define:

```dart
 @BelongsTo(PostBean)
 int postId;
```
from the Item model, while in your Post model:

```dart
@HasMany(ItemBean)
List<Item> items;
```
So it seems easy to visit from Post to Item: You simply preload a `post` object and get a list of `item`s. But the other way needs a bit more work, you have to do:

```dart
post = await postBean.find(item.postId)
```
Is there a simpler way to define `post` as one field of `Item`, then we can do:

```dart
item.post
```

**Comment by tejainece** [comment]
This is not currently possible. Adding a member on the model class might not be possible for generation. However a `findPostFor` (or similar) method on the bean is possible. Would that help you?

**Comment by junjizhi** [comment]
@tejainece yeah. that's how I implemented at the end. Thanks for the reply!

**Comment by elnurvl** [comment]
@tejainece , isn’t it possible at least to add `findFor` kind of functions to generated classes automatically, if the generator finds `@BelongsTo` annotation on models?

**Comment by tejainece** [comment]
Fixed in https://github.com/Jaguar-dart/jaguar_orm/commit/dc166e9a22db0f10cd13440f58d5b5e6348b91ea
