### ISSUE TITLE
Generated removeMany problem with empty list

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#84]
Here is what we generate for `removeMany`

```
 Future<int> removeMany(List<CartItem> models) async {
    final Remove remove = remover;
    for (final model in models) {
      remove.or(this.id.eq(model.id));
    }
    return adapter.remove(remove);
  }
```

Problem is if the list is empty, then we remove the entire table... not that good ^^

**Comment by tejainece** [comment]
Maybe, we should check that `models` is empty. If it is empty, we should just return.

**Comment by jaumard** [comment]
Sure :) but we might want to go further and don't allow empty where statement to prevent erasing data when it's not wanted :/ `adapter.remove(); ` remove everything, `adapter.remove(remove); ` will throw an exception ("need where clause"). I my opinion it will be better to have this as it can be useful for other methods than just removeMany

**Comment by tejainece** [comment]
Agree
