### ISSUE TITLE
SqfliteAdapter batching is unused

### ISSUE THREAD

**Issue by thomasostfeld** [Jaguar-dart/jaguar_orm#85]
Both `updateMany` and `upsertMany` create and commit a batch in `SqfliteAdapter`.

The batch isn't used to execute any of the queries though, they are instead directly handled by the connection.

```
Future<void> upsertMany<T>(UpsertMany st) async {
  List<String> strSt = composeUpsertMany(st);
  final batch = connection.batch();
  for (var query in strSt) {
    connection.execute(query);
  }
  return batch.commit(noResult: true);
}
```

Instead of `connection.execute(query);` the query should be executed by the batch: `batch.execute(query);`

In my test this gave me a big performance boost of about 10x.

**Comment by tejainece** [comment]
Can you make a pr?

**Comment by tejainece** [comment]
@jaumard

**Comment by jaumard** [comment]
nice catch @ozzy91 ! Miss that one :) thanks for the report!
