### ISSUE TITLE
upsert on ManyToMany always inserts join table rows

### ISSUE THREAD

**Issue by shrugs** [Jaguar-dart/jaguar_orm#87]
Howdy! I've implemented a ManyToMany relation following the pattern in the example, and then `upsert`ed a few entries. The join table accumulates entries because there's no de-duplication or other method of determining if the relation already exists.

In my app I have "dots" (users) that can have many "lines" (chats) and "lines" (chats) can have many dots in them.

Here are the (simplified) models.

```dart


class Dot {
  @PrimaryKey(length: 32, isNullable: false)
  String id;

  @ManyToMany(LineMembershipBean, LineBean)
  List<Line> lines;

  Dot({
    this.id,
    this.lines,
  });
}

class LineMembership {
  @BelongsTo.many(DotBean)
  String dotId;

  @BelongsTo.many(LineBean)
  String lineId;

  LineMembership({
    this.dotId,
    this.lineId,
  });
}

class Line {
  @PrimaryKey(length: 32, isNullable: false)
  String id;

  @ManyToMany(LineMembershipBean, DotBean)
  List<Dot> dots;

  @HasOne(ChatBean)
  Chat chat;

  Line({
    this.id,
    this.dots,
    this.chat,
  });
}
```

and here's the relevant generated upsert code

```dart
/// line.jorm.dart
  Future<dynamic> upsert(Line model, {bool cascade: false}) async {
    final Upsert upsert = upserter.setMany(toSetColumns(model));
    var retId = await adapter.upsert(upsert);
    if (cascade) {
      Line newModel;
      if (model.dots != null) {
        newModel ??= await find(model.id);
        for (final child in model.dots) {
          await dotBean.upsert(child, cascade: cascade);
          await lineMembershipBean.attach(model, child);
        }
      }
      if (model.chat != null) {
        newModel ??= await find(model.id);
        chatBean.associateLine(model.chat, newModel);
        await chatBean.upsert(model.chat, cascade: cascade);
      }
    }
    return retId;
  }

/// ......
/// line_membership.jorm.dart
  Future<dynamic> attach(Line one, Dot two) async {
    final ret = LineMembership();
    ret.lineId = one.id;
    ret.dotId = two.id;
    return insert(ret);
  }
```

So when the `upsert` is called, a `LineMembership` is always inserted, and those rows accumulate in the database every time I do a sync from the remote store.

It seems like the expected behavior would be to use `upsert` in `attach` (or provide an `attachUpserted`?) that doesn't fail when it encounters an identical row. Although, that said, perhaps not deduplicating is expected behavior? I'm not sure when that'd be expected. This isn't a problem for when we go to find the association, though, because of how the `fetch*` function is written:

```dart
  Future<List<Dot>> fetchByLine(Line model) async {
    final pivots = await findByLine(model.id);
    if (pivots.isEmpty) return [];
    final exp = Or();
    for (final t in pivots) {
      exp.or(dotBean.id.eq(t.dotId));
    }
    return await dotBean.findWhere(exp);
  }
```

The `.or()` concatenates all of these duplicate records into effectively the same query, but with a lot of bulk and probably wasted processing/optimization from the database engine.

So, what is the expected behavior here?

If no duplicate join rows is intended, how should we de-duplicate them?

**Comment by shrugs** [comment]
Looking around the web, it seems like this was an old problem with rails as well; I haven't been able to find any recent examples of the behavior. the most popular suggestion is to check for the association's existence before writing it, and then back that up with a database unique index across the join table's properties.

**Comment by tejainece** [comment]
Should be fixed by: https://github.com/Jaguar-dart/jaguar_orm/commit/f421f71c607dd20c338fb539a26ba9f5c3e19f10

Could you please test it and let me know if it works?

Thanks!

**Comment by shrugs** [comment]
@tejainece It works! It might be worth noting that the table _must_ have a unique constraint on it for the upsert to do anything. Since my join table doesn't have a primary key, I added a unique index across the two references like so

```dart
class LineMembership {
  @BelongsTo.many(DotBean, uniqueGroup: "dot_to_line")
  String dotId;

  @BelongsTo.many(LineBean, uniqueGroup: "dot_to_line")
  String lineId;

  LineMembership({
    this.dotId,
    this.lineId,
  });
}
```

and now everything is happy. Thanks for the super quick fix!
