### ISSUE TITLE
Generated insert and upsert statements for ManyToMany is using model instead of newModel in cascated attach statement

### ISSUE THREAD

**Issue by MartinHlavna** [Jaguar-dart/jaguar_orm#89]
Eviroment:
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale C.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
[✓] Connected device (1 available)

Steps to reproduce:

1. Implement ManyToMany relation as seen in [example](https://github.com/jaguar-orm/many_to_many)
2. Run build_runner run
3. Run application, invoke TodoListBean.upsert with TodoList that contains Category
4. Upsert will crash on NOT NULL constraint

Technical info:

I have analyzed generated code. Problem is in generated upsert

For example:
```
if (model.posts != null) {
        newModel ??= await find(retId);
        for (final child in model.posts) {
          await postBean.insert(child, cascade: cascade);
          await postTagBean.attach(model, child);
        }
}
```
`await postTagBean.attach(model, child);`

should be

`await postTagBean.attach(newModel, child);`

Because model may not contain id (if it is new object). Same issue may be occour during insert.

It look like problem is in [writer.dart](https://github.com/Jaguar-dart/jaguar_orm/blob/master/generator/lib/src/writer/writer.dart) at lines @267,@269, @373, @375,

**Comment by MartinHlavna** [comment]
#90 should fix this

**Comment by tejainece** [comment]
It has been merged and published.
