### ISSUE TITLE
State which databases are supported in README

### ISSUE THREAD

**Issue by Rockvole** [Jaguar-dart/jaguar_orm#93]
I am having trouble finding out which databases your orm supports. It looks like postgres is supported since the example shows that. I would like to use with mysql but I cannot work out if that is supported.
Also, I would like to use it with flutter sqlite databases, but I cannot tell if the sqlite works with that or only works server side.
Thanks.

**Comment by tejainece** [comment]
[Postgres](https://github.com/Jaguar-dart/jaguar_orm/tree/master/postgres)
[Flutter sqlite](https://github.com/Jaguar-dart/jaguar_orm/tree/master/sqflite)
[mysql/mariadb](https://github.com/Jaguar-dart/jaguar_orm/tree/master/sqljocky)

are supported.

sqlite on desktop is not supported.

Database support for Jaguar ORM is implemented using adapters. If you know of any sqlite drivers on desktop, I can write an adapter.

If you need support, contact us on [gitter](https://gitter.im/jaguar_dart/jaguar).
