### ISSUE TITLE
Add a method to receive the function onCreate / onUpdate / ...

### ISSUE THREAD

**Issue by grasp-algorithm** [Jaguar-dart/jaguar_orm#95]
I think it could be interesting to receive as a parameter on the constructor or in the `connect` method a function to be executed on the `onCreate` or `onUpdate` event.

**Comment by tejainece** [comment]
That is a nice feature! Will add it.

**Comment by hjJunior** [comment]
Sorry, I think this isn't necessary, saw you can use `Adapter.fromConnection`
And else, I think with it will be easier to maintainer, imagine if Sqflite add new callbacks functions

Eg.

```dart
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    final path = join(documentsDirectory.path, "your.db");
    final connection = await sqf.openDatabase(
      path,
      version: 1,
      onUpgrade: doUpgrade,
      onDowngrade: doDowngrade
    );
    final adapter = SqfliteAdapter.fromConnection(connection);
```

**Comment by jaumard** [comment]
Can be useful for other adapters, but yes for sqflite it's useless as it's better to let sqflite manage this
