### ISSUE TITLE
[Help] is it possible to order results?

### ISSUE THREAD

**Issue by hjJunior** [Jaguar-dart/jaguar_orm#96]
Hi, I really appreciate the work of this lib, helped me a lot, actually I'm thinking to build a Flutter bootstrap wrapping good libraries like it.
As well, I did like to know is possible to order results from Find or any another way

like

```
findWhere(this.razaoSocial.like("%$search%")).orderBlabla(...)
```

**Comment by tejainece** [comment]
@hjJunior Thanks for your support and encouraging words!

Here you can find how to build find clauses using jaguar_query: https://github.com/Jaguar-dart/jaguar_orm/wiki/Find-statement

**Comment by tejainece** [comment]
To write conditional expressions, you have to use conditional expression builder of jaguar_query. I am working on the documentation for this: https://github.com/Jaguar-dart/jaguar_orm/wiki/Conditional-expression

**Comment by tejainece** [comment]
Ordering can be performed using `orderBy` method. You can find documentation here: https://github.com/Jaguar-dart/jaguar_orm/wiki/Find-statement#order--sort

**Comment by hjJunior** [comment]
Thxs again ;)
