### ISSUE TITLE
[Help] Many to many only returns distinct pivot table registers

### ISSUE THREAD

**Issue by hjJunior** [Jaguar-dart/jaguar_orm#98]
Hi guys, I'm having some difficulty with many-to-many relations in jaguar orm (Flutter).
I have an `Order` class that register many to many relation with `Product`class using as Pivot table `OrderItem` class

## What is happen
I need to allow my pivot table receives many orderId and productId even if the register is the same (just primary key different), for example if User bought **2 or more** `Product A`  on **same order** and I preload Order class to get product list just returns **distinct products**, at this case returns just only.

### Debugging  
To make sure that that exists looking around of `fetchByOrder` on `order_item.jorm.dart` I edited to be saw the data returned on pivot table, I just add a print to show pivot

```
  Future<List<Product>> fetchByOrder(Order model) async {
    final pivots = await findByOrder(model.id);
    if (pivots.isEmpty) return [];
    final exp = Or();
    for (final t in pivots) {
      exp.or(productBean.id.eq(t.produtoId));
    }
    print(pivots);
    return await productBean.findWhere(exp);
  }
```
And the log will print

```
[OrderItem {id: 1, orderId: 3, produtoId: 4 }, OrderItem {id: 2, orderId: 3, produtoId: 4 }]
```
How can see, exists for same orderId 3 two product of id 4, but after the `productBean.findWhere(exp);` just returns only, is this expect behavior?

### Order class relation definition
```
  @ManyToMany(OrderItemBean, ProductBean)
  List<Product> orderItems;
```

### OrderItem class
```
  @BelongsTo.many(ProductBean)
  int produtoId;

  @BelongsTo.many(OrderBean)
  int orderId;
```

### Product class
```
  @ManyToMany(OrderItemBean, OrderBean)
  List<Order> orders;
```

**Comment by tejainece** [comment]
Currently, this is not supported! I will try to fix this.

**Comment by hjJunior** [comment]
is there any suggestion for me on the project to avoid this problem? 

## Update

I've worked locally, can I open PR with this suggestion?

```
    final List<Product> returnList = [];
    final pivots = await findByOrder(model.id);
    if (pivots.isEmpty) return [];
    final grouped = groupBy(pivots, (OrderItem pivot) => pivot.produtoId);

    for (int i = 0; i < grouped.values.length; i++) {
      final data = await productBean.find(grouped.keys.elementAt(i));
      for (int j = 0; j < grouped.values.elementAt(i).length; j++) {
        returnList.add(data);
      }
    }
    return returnList;
```

**Comment by tejainece** [comment]
A PR to fix this in `jaguar_generator` is welcome!

**Comment by tejainece** [comment]
One suggestions is to turn this behavior on only when a flag named `fetchDuplicates` is set. So that, what one does not expect duplicates, they can get better performance. What do you say?

**Comment by hjJunior** [comment]
Yep, good idea 💡
I will work on this PR.

**Comment by tejainece** [comment]
Thanks man!

Let me know if you need help.

**Comment by tejainece** [comment]
Should be fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/68f78edbad468074e9bd19f0019030b63ff7d813
